[package]
name = "http-storm"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
chrono = "0.4"
tokio = "0.1"
futures = "0.1"
reqwest = { version = "0.9", features = ["trust-dns"] }
