[package]
name = "http-storm"
version = "0.1.0"
edition = "2018"

[dependencies]
average = "0.10"
chrono = "0.4"
clap = { version = "2.33", features = ["yaml"] }
futures = "0.3"
reqwest = "0.10"
termion = "1.5"
tokio = { version = "0.2", features = ["full"] }
tui = "0.8"
